mod config;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use owo_colors::OwoColorize;
use std::path::PathBuf;
use std::process::ExitCode;

#[derive(Parser)]
#[command(
    name = "valiforge",
    version,
    about = "Headless API validation engine for the AI coding era",
    long_about = "ValiForge validates API contracts, detects breaking changes,\n\
                  and generates test data — all from a single Rust binary.\n\n\
                  Validate APIs, not pixels."
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,

    /// Path to configuration file
    #[arg(long, global = true, default_value = "valiforge.toml")]
    config: PathBuf,

    /// Output format
    #[arg(long, global = true, default_value = "terminal")]
    format: OutputFormat,

    /// Suppress all output except errors
    #[arg(long, global = true)]
    quiet: bool,

    /// Enable verbose output
    #[arg(long, global = true)]
    verbose: bool,
}

// Doc comments here are CLI help text, where backticks would print literally.
#[allow(clippy::doc_markdown)]
#[derive(Subcommand)]
enum Commands {
    /// Initialize ValiForge in the current project
    Init {
        /// Accept all defaults without prompting
        #[arg(long)]
        yes: bool,
    },
    /// Validate API endpoints against schema
    Validate {
        /// Path to API schema file
        #[arg(long)]
        schema: Option<PathBuf>,
        /// Base URL of the API to validate
        #[arg(long)]
        target: Option<String>,
    },
    /// Detect breaking changes between schema versions
    Diff {
        /// Path to the old (current) schema
        old: PathBuf,
        /// Path to the new (proposed) schema
        new: PathBuf,
    },
    /// Generate test data from schema
    Generate {
        /// Path to API schema
        #[arg(long)]
        schema: PathBuf,
        /// Number of payloads to generate
        #[arg(long, default_value = "10")]
        count: usize,
        /// Include negative test cases
        #[arg(long)]
        include_negative: bool,
    },
}

#[derive(Clone, clap::ValueEnum)]
enum OutputFormat {
    Terminal,
    Json,
    Junit,
    Markdown,
}

#[tokio::main]
async fn main() -> ExitCode {
    let cli = Cli::parse();

    let filter = if cli.verbose {
        "valiforge=debug"
    } else if cli.quiet {
        "error"
    } else {
        "valiforge=info"
    };
    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_target(false)
        .init();

    match run(cli).await {
        Ok(success) => {
            if success {
                ExitCode::from(0)
            } else {
                ExitCode::from(1)
            }
        }
        Err(e) => {
            eprintln!("{} {e:#}", "error:".red().bold());
            ExitCode::from(2)
        }
    }
}

#[allow(clippy::too_many_lines)]
async fn run(cli: Cli) -> Result<bool> {
    match cli.command {
        Commands::Init { yes: _ } => {
            let schemas = valiforge_schema::detect::detect_schemas(&std::env::current_dir()?);

            if schemas.is_empty() {
                println!(
                    "{} No API schemas detected. Create an openapi.yaml and re-run.",
                    "warning:".yellow().bold()
                );
                return Ok(true);
            }

            println!(
                "{} Detected {} schema(s):",
                "info:".blue().bold(),
                schemas.len()
            );
            for s in &schemas {
                println!("  {}", s.display().green());
            }

            let config_content = format!(
                r#"# ValiForge Configuration
# Generated by `valiforge init`

[schema]
path = "{}"

[target]
base_url = "http://localhost:3000"
timeout = "10s"

[validation]
fail_on = ["schema-violations"]

[reporting]
formats = ["terminal"]
"#,
                schemas[0].display()
            );

            std::fs::write("valiforge.toml", &config_content)
                .context("Failed to write valiforge.toml")?;

            println!("\n{} Created valiforge.toml", "success:".green().bold());
            println!("\nNext steps:");
            println!("  1. Start your API server");
            println!(
                "  2. Run {} to validate",
                "valiforge validate".cyan().bold()
            );

            Ok(true)
        }

        Commands::Validate { schema, target } => {
            let cfg = config::load_config(&cli.config)?;
            let schema_path = schema.or(cfg.schema_path).context(
                "No schema specified. Use --schema or set [schema].path in valiforge.toml",
            )?;
            let target_url = target
                .or(cfg.target_url)
                .unwrap_or_else(|| "http://localhost:3000".into());

            let endpoints = valiforge_schema::parse_openapi_file(&schema_path)
                .context("Failed to parse schema")?;

            println!(
                "{} Validating {} endpoints against {}",
                "info:".blue().bold(),
                endpoints.len().to_string().cyan(),
                target_url.cyan()
            );

            let ctx = valiforge_core::ValidationContext {
                target_url: target_url.parse().context("Invalid target URL")?,
                ..Default::default()
            };

            let engine = valiforge_core::ValidationEngine::new(ctx)
                .context("Failed to create validation engine")?;

            let report = engine
                .validate_all(&endpoints, &schema_path.display().to_string())
                .await
                .context("Validation failed")?;

            println!("\n{}", "Results:".bold());
            for r in &report.results {
                let icon = match r.status {
                    valiforge_core::ValidationStatus::Pass => "PASS".green().to_string(),
                    valiforge_core::ValidationStatus::Fail => "FAIL".red().to_string(),
                    valiforge_core::ValidationStatus::Skip => "SKIP".yellow().to_string(),
                    valiforge_core::ValidationStatus::Error => "ERR ".red().bold().to_string(),
                };
                println!(
                    "  {} {} {} ({}ms)",
                    icon,
                    r.method.bold(),
                    r.path,
                    r.latency.as_millis()
                );
                for v in &r.violations {
                    println!("       {} {}", "->".dimmed(), v.message);
                }
            }

            println!(
                "\n{}: {} total, {} passed, {} failed, {} errors",
                "Summary".bold(),
                report.summary.total,
                report.summary.passed.to_string().green(),
                report.summary.failed.to_string().red(),
                report.summary.errors.to_string().red(),
            );

            Ok(report.is_success())
        }

        Commands::Diff { old, new } => {
            let old_content = std::fs::read_to_string(&old)
                .context(format!("Failed to read {}", old.display()))?;
            let new_content = std::fs::read_to_string(&new)
                .context(format!("Failed to read {}", new.display()))?;

            let old_endpoints = valiforge_schema::openapi::parse_openapi_string(&old_content)?;
            let new_endpoints = valiforge_schema::openapi::parse_openapi_string(&new_content)?;

            println!(
                "{} Comparing {} -> {}",
                "info:".blue().bold(),
                old.display().to_string().cyan(),
                new.display().to_string().cyan()
            );

            let mut breaking = Vec::new();
            for old_ep in &old_endpoints {
                let exists = new_endpoints
                    .iter()
                    .any(|n| n.method == old_ep.method && n.path == old_ep.path);
                if !exists {
                    breaking.push(valiforge_core::BreakingChange {
                        change_type: valiforge_core::ChangeType::EndpointRemoved,
                        severity: valiforge_core::Severity::Critical,
                        path: format!("{} {}", old_ep.method, old_ep.path),
                        message: format!("Endpoint {} {} was removed", old_ep.method, old_ep.path),
                        old_value: Some(format!("{} {}", old_ep.method, old_ep.path)),
                        new_value: None,
                    });
                }
            }

            if breaking.is_empty() {
                println!(
                    "\n{} No breaking changes detected.",
                    "success:".green().bold()
                );
                Ok(true)
            } else {
                println!(
                    "\n{} {} breaking change(s) detected:",
                    "warning:".red().bold(),
                    breaking.len()
                );
                for change in &breaking {
                    println!(
                        "  {} [{}] {}",
                        "BREAK".red().bold(),
                        format!("{:?}", change.change_type).yellow(),
                        change.message
                    );
                }
                Ok(false)
            }
        }

        Commands::Generate {
            schema,
            count,
            include_negative: _,
        } => {
            println!(
                "{} Generating {} test payloads from {}",
                "info:".blue().bold(),
                count.to_string().cyan(),
                schema.display().to_string().cyan()
            );
            println!(
                "{} Test data generation will be available with valiforge-datagen",
                "todo:".yellow().bold()
            );
            Ok(true)
        }
    }
}
